apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: multi-miner-sigkill
spec:
  tracepoints:
    - subsystem: raw_syscalls
      event: sys_exit
      # args: syscall id
      args:
      - index: 4
        type: int64
      selectors:
      - matchArgs:
        - index: 4
          operator: Equal
          values:
          - "59"
          - "322"
        matchBinaries:
        - operator: In
          values:
          - "./xmrig"
          - "./kill_miner"
          - "./titcoind"
          - "./cpuminer"
          - "./nanominer"
          - "./minerd"
          - "./pwnrig"
          - "./ccminer"
        matchActions:
        - action: Sigkill
